### PR TITLE
created user allows access to the HTTP API

### PR DESCRIPTION
**Pull request by SoulHunt3r**
**Description of the change**

created user allows access to the HTTP API
* tomcat 9
* tomcat 10

**Benefits**

**Possible drawbacks**

**Applicable issues**

**Additional information**

### CODE REVIEW

**Review by marcosbc — CHANGES_REQUESTED** [review]
Hi @SoulHunt3r, I'm a bit concerned with this change. Would it not introduce security vulnerabilities by allowing remote .war execution?

If there is any security risk, I would prefer to leave this option to be configurable via an environment variable, i.e. `TOMCAT_ENABLE_MANAGER_API` and that is disabled by default.

**Comment by SoulHunt3r** [comment]
> If there is any security risk, I would prefer to leave this option to be configurable via an environment variable, i.e. `TOMCAT_ENABLE_MANAGER_API` and that is disabled by default.

if setting environment variable `TOMCAT_ENABLE_MANAGER_API=1` will lead to user creation with roles including "manager-script", allowing use of HTTP API - sounds good enough.

**Comment by SoulHunt3r** [comment]
best one - have more than one to create, cause remended to have separate users for roles manager-gui and manager-script

**Comment by migruiz4** [comment]
Hi @SoulHunt3r,

I agree with @marcosbc that API privilege shouldn't be configured by default and instead, it should include an additional variable to control it.

Creating multiple users is not a bad idea either, but could become more confusing in the future: `TOMCAT_USER`, `TOMCAT_API_USER`, `TOMCAT_?_USER`...

In case you would like to create multiple users with different roles, I would suggest adding support for `init_scripts` so users can mount custom scripts to create users based on their needs.

As a reference, you can check other bitnami images, for example:
**setup.sh** https://github.com/bitnami/bitnami-docker-elasticsearch/blob/d0c6531f6c9b0c21cb0b7dd2f127677cc07e649c/7/debian-10/rootfs/opt/bitnami/scripts/elasticsearch/setup.sh#L30-L31 
**libapp.sh** https://github.com/bitnami/bitnami-docker-elasticsearch/blob/d0c6531f6c9b0c21cb0b7dd2f127677cc07e649c/7/debian-10/rootfs/opt/bitnami/scripts/libelasticsearch.sh#L600-L634

**Pull request closed without merging**
